amcl:
  ros__parameters:
    use_sim_time: true
    expected_map_rate: 1.0
    scan_topic: scan
    base_frame_id: "base_footprint"
    odom_frame_id: "odom"
    global_frame_id: "map"
    min_particles: 500
    max_particles: 2000
    initial_pose: {x: 0.0, y: 0.0, z: 0.0, yaw: 0.0}
    set_initial_pose: true  # FORCE INITIAL POSE TO FIX MAP FRAME

map_server:
  ros__parameters:
    use_sim_time: true
    frame_id: map
    # ABSOLUTE PATH HARDCODED
    yaml_filename: "/home/anish/gazebo_ros_ws/src/warehouse_robot/maps/warehouse_map.yaml"

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    bond_timeout: 0.0
    node_names: ['map_server', 'amcl']
